django_selenium_lab/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('scraper/', include('scraper.urls')),
]

scraper/urls.py
from django.urls import path
from . import views

app_name = 'scraper'

urlpatterns = [
    path('', views.course_list, name='course_list'),
    path('list_all/', views.course_list_all, name='course_list_all'),
    path('collect/', views.collect_courses, name='collect_courses'),
]

scraper/models.py
from django.db import models

# Create your models here.

class CeleryTestModel(models.Model):
    text = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text
    class Meta:
        db_table = "celery_test_model" # テーブル名を指定


class Syllabus(models.Model):
    course_name = models.CharField(max_length=100)
    course_url = models.URLField(max_length=200)
    course_year = models.CharField(
        max_length=4,
        default='yet'
        )
    course_department = models.CharField(max_length=100, default='学部不明')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.course_name
    class Meta:
        db_table = "syllabus"

scraper/views.py
from django.shortcuts import render, redirect
from django.db.models import Q

from .models import Syllabus
from .tasks import collect_syllabus_to_db_task
from .utils import split_whitespace


# Create your views here.


def course_list(request):
    courses = Syllabus.objects.all()

    query = request.GET.get('search_query')
    if not query:
        # 初回アクセスや空入力は全件（ポリシーに応じて空リストでもOK）
        return render(request, 'scraper/course_list.html', {'courses': courses})

    querys = split_whitespace(query)
    # for で filter を繰り返すと AND 検索になる
    for q in querys:
        courses = courses.filter(
            Q(course_name__icontains=q) |
            Q(course_department__icontains=q)
        )

    return render(request, 'scraper/course_list.html', {'courses': courses})


def course_list_all(request):
    Syllabus.objects.all()
    return redirect('scraper:course_list')


def collect_courses(request):
    collect_syllabus_to_db_task.delay()
    return redirect('scraper:course_list')

scraper/templates/base.html
<!-- アプリを拡張するなら`templates/base.html`だけ proj 直下に置く -->
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
{% block content %}
{% endblock content %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>

scraper/templates/scraper/course_list.html
{% extends "base.html" %}

{% block title %}
Course List
{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Lecture List</h1>

    <!-- 講義情報を収集する -->
    <form action="{% url 'scraper:collect_courses' %}" method="POST">
        {% csrf_token %}
        <button class="btn btn-primary" type="submit">講義名を収集</button>
    </form>

    <h2 class="mt-4">講義を検索</h2>

    <form action="{% url 'scraper:course_list_all' %}" method="POST">
        {% csrf_token %}
        <button class="btn btn-primary" type="submit">すべての講義を表示</button>
    </form>
    <form class="d-flex" role="search"  method="GET">
        <input class="form-control me-2" type="search" name = "search_query" placeholder="講義名 または学部を入力" aria-label="Search" required>
    <button class="btn btn-outline-success" type="submit">Search</button>
    </form>


    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Course Name</th>
                <th scope="col">Department</th>
                <th scope="col">Course Year</th>
                <th scope="col">Course Url</th>
            </tr>
        </thead>
        {% if courses %}
        <tbody>
            {% for course in courses %}
            <tr>
                <td>{{ course.id }}</td>
                <td>{{ course.course_name }}</td>
                <td>{{ course.course_department }}</td>
                <td>{{ course.course_year }}</td>
                <td><a href="{{ course.course_url }}">{{ course.course_url }}</a></td>
            </tr>
            {% endfor %}
        </tbody>
        {% else %}
        <p>まだ講義が取得されていません。</p>
        {% endif %}
    </table>


{% endblock content %}